/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoFacetResult.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto.common {

[Bindable]
public class DtoFacetResultBase {
    public function DtoFacetResultBase(){
    }

    public var qFacetFields:Array;
    public var qMaxFacetTermNum:int;
    public var qRowNum:Number;
    public var qStartRow:Number;
    public var queryStr:String;
    public var rFacetsRecords:Object;
    public var rNumFound:Number;
    public var rQueryRecords:Array;
    public var rStartRow:Number;
}

}