/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Dto3DConfig.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class Dto3DConfigBase {
    public function Dto3DConfigBase(){
    }

    public var preload3dModelDepth:int;
    public var root3dstructure:int;
    public var scale3d:int;
    public var scaleSection:int;
    public var spaceFromX:int;
    public var spaceFromY:int;
    public var spaceFromZ:int;
    public var spaceToX:int;
    public var spaceToY:int;
    public var spaceToZ:int;
    public var unitLength:int;
}

}