/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

[Bindable]
[RemoteClass(alias="edu.umich.med.mbni.pubanatomy.flash.dto.Dto3DConfig")]
public class Dto3DConfig extends Dto3DConfigBase {
    private var _dataExt:Array;
    public function get dataExtent():Array{
        if( _dataExt == null ){
            _dataExt = [ spaceFromX, spaceToX, spaceFromY, spaceToY, spaceFromZ, spaceToZ ];
        }
        return _dataExt;
    }
}
}