/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoException.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoExceptionBase {
    public function DtoExceptionBase(){
    }

    public var code:int;
    public var stack:String;
}

}