/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

    [Bindable]
    [RemoteClass(alias="edu.umich.med.mbni.pubanatomy.flash.dto.DtoException")]
    public class DtoException extends DtoExceptionBase {
    }
}