/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoFacetResultMedline.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

import edu.umich.med.mbni.pubanatomy.flash.dto.common.DtoFacetResult;

[Bindable]
public class DtoFacetResultMedlineBase extends DtoFacetResult {
    public function DtoFacetResultMedlineBase(){
    }

}

}