/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoGene.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoGeneBase {
    public function DtoGeneBase(){
    }

    public var acronym:String;
    public var aliasTags:String;
    public var chromosomeId:Number;
    public var ensemblId:Number;
    public var entrezId:Number;
    public var geneId:int;
    public var homoloGeneId:Number;
    public var legacyEnsemblGeneId:Number;
    public var name:String;
    public var organismId:Number;
    public var sphinxId:Number;
    public var type:String;
}

}