/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {
import flash.utils.Dictionary;

[Bindable]
[RemoteClass(alias="edu.umich.med.mbni.pubanatomy.flash.dto.DtoGeneExprLevel")]
public class DtoGeneExprLevel extends DtoGeneExprLevelBase {

    public function DtoGeneExprLevel(){
        super();
    }

    public var structureId2VoxelLevels:Dictionary;
}
}