/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoGeneExprLevel.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoGeneExprLevelBase {
    public function DtoGeneExprLevelBase(){
    }

    public var sectionDataSetId:Number;
    public var type:String;
    public var unitLen:int;
    public var voxelLevels:Array;
}

}