/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoGeneExprAnnotation.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoGeneExprAnnotationBase {
    public function DtoGeneExprAnnotationBase(){
    }

    public var structureId:Array;
    public var unitlen:int;
    public var x:Array;
    public var y:Array;
    public var z:Array;
}

}