/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoImageSection.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

import mx.collections.ListCollectionView;

[Bindable]
public class DtoImageSectionBase {
    public function DtoImageSectionBase(){
    }

    public var edges:ListCollectionView;
    public var imageId:Number;
    public var model:DtoModel;
}

}