/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoModelMesh.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoModelMeshBase {
    public function DtoModelMeshBase(){
    }

    public var indexes:Array;
    public var normals:Array;
    public var owner:DtoModelMeshArray;
    public var vertices:Array;
}

}