/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoResultRecordMedline.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoResultRecordMedlineBase {
    public function DtoResultRecordMedlineBase(){
    }

    public var abstractTexts:Array;
    public var articleAffiliation:String;
    public var articleAuthorFullNames:Array;
    public var articleAuthorListCollectives:Array;
    public var articleAuthorListForeNames:Array;
    public var articleAuthorListInitials:Array;
    public var articleAuthorListLastNames:Array;
    public var articleAuthorListSuffixs:Array;
    public var articleJournalIsoAbbrev:String;
    public var articleJournalIssn:String;
    public var articleJournalIssueIssue:String;
    public var articleJournalIssueVolume:String;
    public var articleJournalPubDateMedlineDate:String;
    public var articleJournalPubDateYear:Number;
    public var articleJournalTitle:String;
    public var articleLangs:Array;
    public var articlePaginationMedlinePgn:Array;
    public var articlePublicationTypeList:Array;
    public var articleTitle:String;
    public var brainStructureIds:Array;
    public var brainStructureNames:Array;
    public var brainStructureSymbols:Array;
    public var chemicalNameOfSubstances:Array;
    public var chemicalRegistryNumbers:Array;
    public var diseases:Array;
    public var functions:Array;
    public var geneIds:Array;
    public var geneNames:Array;
    public var geneSymbols:Array;
    public var grantAcronyms:Array;
    public var grantAgencis:Array;
    public var grantCountries:Array;
    public var grantIds:Array;
    public var investigatorList:Array;
    public var journalCountry:String;
    public var journalMedlineTa:String;
    public var journalNlmUniqueId:String;
    public var keywordList_majorTopic_n:Array;
    public var keywordList_majorTopic_y:Array;
    public var keywords:Array;
    public var meshHeadingDescNames:Array;
    public var meshHeadingDescNames_majorTopic_n:Array;
    public var meshHeadingDescNames_majorTopic_y:Array;
    public var meshHeadingQualifierNames:Array;
    public var meshHeadingQualifierNames_majorTopic_n:Array;
    public var meshHeadingQualifierNames_majorTopic_y:Array;
    public var otherAbstractTexts:Array;
    public var pmid:Number;
    public var protocols:Array;
}

}