/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoSection.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

import mx.collections.ListCollectionView;

[Bindable]
public class DtoSectionBase {
    public function DtoSectionBase(){
    }

    public var edges:ListCollectionView;
    public var model:DtoModel;
    public var plane:DtoPlane;
}

}