/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoSearchHighValueTermNum.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {


[Bindable]
public class DtoSearchHighValueTermNumBase {
    public function DtoSearchHighValueTermNumBase(){
    }

    public var globalFound:Number;
    public var subFound:Number;
    public var term:String;
}

}