/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoSearchHighValueTerms.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

import mx.collections.ListCollectionView;

[Bindable]
public class DtoSearchHighValueTermsBase {
    public function DtoSearchHighValueTermsBase(){
    }

    public var globalDocNum:Number;
    public var subDocNum:Number;
    public var terms:ListCollectionView;
}

}