/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {
import mx.collections.IList;

[Bindable]
[RemoteClass(alias="edu.umich.med.mbni.pubanatomy.flash.dto.DtoSection")]
public class DtoSection extends DtoSectionBase implements IModelSectionEdge{
    public function DtoSection(){
        super();
    }

    public function equals( a:IModelSectionEdge ):Boolean{
        var another:DtoSection = a as DtoSection;
        return another != null && another.model.equals( model ) && another.plane.equals( plane );
    }

    public function getModel():DtoModel{
        return model;
    }

    public function getEdge():IList{
        return edges;
    }
}
}