/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {
import flash.utils.Dictionary;

[Bindable]
    [RemoteClass(alias="edu.umich.med.mbni.pubanatomy.flash.dto.DtoStructure")]
    public class DtoStructure extends DtoStructureBase {
        public function DtoStructure(){
            super();
        }

        //todo:dirty!!
        public static var structureSymbol2Item:Dictionary = new Dictionary();
        public static var structureSymbol2ItemDto:Dictionary = new Dictionary();

    }
}