/**
 * Generated by Gas3 v2.3.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (DtoStructure.as).
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

import mx.collections.ListCollectionView;

[Bindable]
public class DtoStructureBase {
    public function DtoStructureBase(){
    }

    public var acronym:String;
    public var atlasId:int;
    public var children:ListCollectionView;
    public var color:String;
    public var depth:int;
    public var graphId:int;
    public var hemisphereId:int;
    public var max:Array;
    public var min:Array;
    public var name:String;
    public var ontologyId:int;
    public var parent:DtoStructure;
    public var pointsNum:Number;
    public var sectionModel:DtoModel;
    public var structureId:int;
    public var visualModel:DtoModel;
    public var weight:int;
}

}