/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package edu.umich.med.mbni.pubanatomy.flash.dto {

    [Bindable]
    [RemoteClass(alias="edu.umich.med.mbni.pubanatomy.flash.dto.DtoVoxelLevel")]
    public class DtoVoxelLevel extends DtoVoxelLevelBase {
        public function DtoVoxelLevel(){
            super();
        }



        /**
         * not binding these 2 !!!
         */
        private var _color:uint;
        private var _alpha:Number;

        public function get color():uint{
            return _color;
        }


        public function get alpha():Number{
            return _alpha;
        }

        public function setAlphaColor( alpha:Number, color:uint ):void{
            _alpha = alpha;
            _color = color;
        }

    }
}